name: Pipeline 1.0

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.5.1 torchvision==0.20.1 --index-url https://download.pytorch.org/whl/cu124
          pip install -r requirements.txt
          python -m spacy download en_core_web_sm
      
      - name: Remove old DB
        run: rm -f onto_db/onto_new.db

      - name: Run data preprocessing
        run: |
          python -m pre_processing.patterns
          python -m pre_processing.data_preprocessing
          python -m pre_processing.contextual_chunking
          python -m pipeline.pipeline_processing


      - name: Run OLAF pipeline
        run: |
          python -m olaf.term_extraction_tfidf
          python -m olaf.term_enrichment
          python -m olaf.embeddings
          python -m olaf.parent_terms
          python -m olaf.taxonomy
          python -m olaf.non_taxonomy


